{% set name = "tippecanoe" %}
{% set version = "1.36.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mapbox//{{ name }}/archive/{{ version }}.tar.gz
  sha256: 0e385d1244a0d836019f64039ea6a34463c3c2f49af35d02c3bf241aec41e71b

build:
  skip: true  # [win]
  number: 2
  script:
    - ls
    - make -j$CPU_COUNT
    - make install

requirements:
  build:
    - make
    - {{ compiler ('c') }}
    - {{ compiler ('cxx') }}
  host:
    - sqlite
    - zlib

test:
  commands:
    - which tippecanoe
    - tippecanoe --help

about:
  home: https://github.com/mapbox/tippecanoe
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Build vector tilesets from large collections of GeoJSON features.

extra:
  recipe-maintainers:
    - jonaslalin
    - mxr-conda
    - adbeda
    - rluria14
    - oblute
