{% set name = "tippecanoe" %}
{% set version = "1.35.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    url: https://github.com/mapbox//{{name}}/archive/{{ version }}.tar.gz
    sha256: 4a31ef5ba1288eb17f9d52a7d84fef9432f13756af9d2c243d46309d6ff09488

build:
  skip: true   # [win]
  number: 0
  script:
    - ls
    - make -j$CPU_COUNT
    - make install

requirements:
  build:
    - make
    - {{ compiler ('c') }}
    - {{ compiler ('cxx') }}
  host:
    - sqlite
    - zlib

test:
  commands:
    - which tippecanoe
    - tippecanoe --help

about:
  home: https://github.com/mapbox/tippecanoe
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: "Build vector tilesets from large collections of GeoJSON features."

extra:
  recipe-maintainers:
    - adbeda
