travis:
  secure:
    BINSTAR_TOKEN: chBbBQbVp5XKHpAslyyVumKiPP07hQUChiTAIUDVTC1TFAZAY7HkByI5m3X5s90QTszvEjP20CK6rBAGEx7rX+r5Xgb6weCll/cet021L2RDmBqgB8FmRNVdsFj5OrcpavY7sVnV2s455kLTgEBvCUBRi/air4PAOQ4+tku0Cl/NDopScgdl2DgqC+CTb2iI8sDWuYrnFsGAaXvNQs/Gpr+MQaDPwDEB2TjXs7eQfHurppSoMNFsBotZp7yls/t3K1UD7f1qadq4/i/jxaPW8dd6nW1dye4gjiz4XdrAlHG1LGgpFgxjOpaw3i+lPPJY/CI5aqJ6VVv0HPks9VlfmLNPAUidYttR2b9zXZhFxkk12DAU9zbuiGmphUF5EptKXSlux9Wbk918YVo/w/CBXF/JiJ9t2y+eHXRNCuEqxYjPJxMb7/TZ0ptO82BgxYVXSua0jPAlil5ITlu2aXQD6IANERuW8KXl9jIXW/aUiVqLeLthicYrlxnt4xEIvouyJ0BnHIW40/fBC6r6cy4uray4U5YnhSYFYBZSuzQ1KpF+uHPKdnF0hCLLPphxotvexKvz3+BDeN+VFZoNoOcqHtjPUTENz3r3+KghqQyxVS221xiEtjDw8N4RPsPHlEyEZsiw4+5SWDc0fLn84Z3USEK9Z0IQE1wE1bYNma47HT8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
